# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alternativepedidosanteriores.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(935, 707)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTitulo = QtWidgets.QLabel(self.centralwidget)
        self.labelTitulo.setMinimumSize(QtCore.QSize(0, 50))
        self.labelTitulo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitulo.setObjectName("labelTitulo")
        self.verticalLayout.addWidget(self.labelTitulo)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 915, 573))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frameContenedor = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frameContenedor.setMaximumSize(QtCore.QSize(16777215, 400))
        self.frameContenedor.setStyleSheet("QFrame{\n"
"    background-color:#a8cbed;\n"
"}\n"
"\n"
"QTableWidget{\n"
"    background-color:white;\n"
"}\n"
"\n"
"QLabel{\n"
"    font-size: 15px;\n"
"}")
        self.frameContenedor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameContenedor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameContenedor.setObjectName("frameContenedor")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameContenedor)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelIDPedido = QtWidgets.QLabel(self.frameContenedor)
        self.labelIDPedido.setObjectName("labelIDPedido")
        self.horizontalLayout_2.addWidget(self.labelIDPedido)
        self.lineIDdelPedido = QtWidgets.QLineEdit(self.frameContenedor)
        self.lineIDdelPedido.setObjectName("lineIDdelPedido")
        self.horizontalLayout_2.addWidget(self.lineIDdelPedido)
        spacerItem = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.labelNombreCliente = QtWidgets.QLabel(self.frameContenedor)
        self.labelNombreCliente.setObjectName("labelNombreCliente")
        self.horizontalLayout_2.addWidget(self.labelNombreCliente)
        self.lineNombreDelCliente = QtWidgets.QLineEdit(self.frameContenedor)
        self.lineNombreDelCliente.setObjectName("lineNombreDelCliente")
        self.horizontalLayout_2.addWidget(self.lineNombreDelCliente)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.espaciador1 = QtWidgets.QFrame(self.frameContenedor)
        self.espaciador1.setMinimumSize(QtCore.QSize(30, 0))
        self.espaciador1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.espaciador1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.espaciador1.setObjectName("espaciador1")
        self.horizontalLayout_3.addWidget(self.espaciador1)
        self.tablaProductos = QtWidgets.QTableWidget(self.frameContenedor)
        self.tablaProductos.setMinimumSize(QtCore.QSize(650, 200))
        self.tablaProductos.setStyleSheet("")
        self.tablaProductos.setObjectName("tablaProductos")
        self.tablaProductos.setColumnCount(4)
        self.tablaProductos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablaProductos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaProductos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaProductos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaProductos.setHorizontalHeaderItem(3, item)
        self.horizontalLayout_3.addWidget(self.tablaProductos)
        self.espaciador2 = QtWidgets.QFrame(self.frameContenedor)
        self.espaciador2.setMinimumSize(QtCore.QSize(30, 0))
        self.espaciador2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.espaciador2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.espaciador2.setObjectName("espaciador2")
        self.horizontalLayout_3.addWidget(self.espaciador2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label_4 = QtWidgets.QLabel(self.frameContenedor)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frameContenedor)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_4.addWidget(self.lineEdit_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.addWidget(self.frameContenedor)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(528, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.btnCerrar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCerrar.setMinimumSize(QtCore.QSize(120, 50))
        self.btnCerrar.setObjectName("btnCerrar")
        self.horizontalLayout.addWidget(self.btnCerrar)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelTitulo.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Pedidos anteriores:</span></p></body></html>"))
        self.labelIDPedido.setText(_translate("MainWindow", "ID del pedido:"))
        self.labelNombreCliente.setText(_translate("MainWindow", "Nombre del Cliente"))
        item = self.tablaProductos.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Producto"))
        item = self.tablaProductos.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Precio Unitario"))
        item = self.tablaProductos.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Cantidad"))
        item = self.tablaProductos.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Precio Total"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">TOTAL:</span></p></body></html>"))
        self.btnCerrar.setText(_translate("MainWindow", "Cerrar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
