# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'framePedido.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(742, 400)
        Frame.setMinimumSize(QtCore.QSize(0, 400))
        self.verticalLayout = QtWidgets.QVBoxLayout(Frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelIDPedido = QtWidgets.QLabel(Frame)
        self.labelIDPedido.setObjectName("labelIDPedido")
        self.horizontalLayout_2.addWidget(self.labelIDPedido)
        self.lineIDdelPedido = QtWidgets.QLineEdit(Frame)
        self.lineIDdelPedido.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineIDdelPedido.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineIDdelPedido.setObjectName("lineIDdelPedido")
        self.horizontalLayout_2.addWidget(self.lineIDdelPedido)
        spacerItem = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.labelNombreCliente = QtWidgets.QLabel(Frame)
        self.labelNombreCliente.setObjectName("labelNombreCliente")
        self.horizontalLayout_2.addWidget(self.labelNombreCliente)
        self.lineNombreDelCliente = QtWidgets.QLineEdit(Frame)
        self.lineNombreDelCliente.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineNombreDelCliente.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineNombreDelCliente.setObjectName("lineNombreDelCliente")
        self.horizontalLayout_2.addWidget(self.lineNombreDelCliente)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.espaciador1 = QtWidgets.QFrame(Frame)
        self.espaciador1.setMinimumSize(QtCore.QSize(30, 0))
        self.espaciador1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.espaciador1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.espaciador1.setObjectName("espaciador1")
        self.horizontalLayout_3.addWidget(self.espaciador1)
        self.tablaProductos = QtWidgets.QTableWidget(Frame)
        self.tablaProductos.setMinimumSize(QtCore.QSize(650, 200))
        self.tablaProductos.setStyleSheet("")
        self.tablaProductos.setObjectName("tablaProductos")
        self.tablaProductos.setColumnCount(4)
        self.tablaProductos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablaProductos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaProductos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaProductos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaProductos.setHorizontalHeaderItem(3, item)
        self.horizontalLayout_3.addWidget(self.tablaProductos)
        self.espaciador2 = QtWidgets.QFrame(Frame)
        self.espaciador2.setMinimumSize(QtCore.QSize(30, 0))
        self.espaciador2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.espaciador2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.espaciador2.setObjectName("espaciador2")
        self.horizontalLayout_3.addWidget(self.espaciador2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelMetodoPago = QtWidgets.QLabel(Frame)
        self.labelMetodoPago.setObjectName("labelMetodoPago")
        self.horizontalLayout_4.addWidget(self.labelMetodoPago)
        self.lineMetodoPago = QtWidgets.QLineEdit(Frame)
        self.lineMetodoPago.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lineMetodoPago.setObjectName("lineMetodoPago")
        self.horizontalLayout_4.addWidget(self.lineMetodoPago)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.labelTotal = QtWidgets.QLabel(Frame)
        self.labelTotal.setObjectName("labelTotal")
        self.horizontalLayout_4.addWidget(self.labelTotal)
        self.lineTotal = QtWidgets.QLineEdit(Frame)
        self.lineTotal.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineTotal.setObjectName("lineTotal")
        self.horizontalLayout_4.addWidget(self.lineTotal)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.labelIDPedido.setText(_translate("Frame", "ID del pedido:"))
        self.labelNombreCliente.setText(_translate("Frame", "Nombre del Cliente:"))
        item = self.tablaProductos.horizontalHeaderItem(0)
        item.setText(_translate("Frame", "Producto"))
        item = self.tablaProductos.horizontalHeaderItem(1)
        item.setText(_translate("Frame", "Precio Unitario"))
        item = self.tablaProductos.horizontalHeaderItem(2)
        item.setText(_translate("Frame", "Cantidad"))
        item = self.tablaProductos.horizontalHeaderItem(3)
        item.setText(_translate("Frame", "Precio Total"))
        self.labelMetodoPago.setText(_translate("Frame", "Metodo de Pago:"))
        self.labelTotal.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">TOTAL:</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
