# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frameMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(845, 70)
        Frame.setMaximumSize(QtCore.QSize(16777215, 70))
        Frame.setStyleSheet("\n"
"QFrame{\n"
"    \n"
"    background-color: rgb(155, 222, 255);\n"
"}\n"
"QLabel{\n"
"    \n"
"    font: 25 13pt \"Ubuntu\";\n"
"    background-color: rgb(0, 170, 255);\n"
"}\n"
"QPushButton{\n"
"    font: 25 12pt \"Ubuntu\";\n"
"    background-color: rgb(170, 255, 0);\n"
"}\n"
"QSpinBox{\n"
"    font: 25 12pt \"Ubuntu\";\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelNombreProducto = QtWidgets.QLabel(Frame)
        self.labelNombreProducto.setAlignment(QtCore.Qt.AlignCenter)
        self.labelNombreProducto.setObjectName("labelNombreProducto")
        self.horizontalLayout.addWidget(self.labelNombreProducto)
        self.labelPrecioProducto = QtWidgets.QLabel(Frame)
        self.labelPrecioProducto.setStyleSheet("background-color: rgb(155, 222, 255);\n"
"font-weight: bold;\n"
"")
        self.labelPrecioProducto.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPrecioProducto.setObjectName("labelPrecioProducto")
        self.horizontalLayout.addWidget(self.labelPrecioProducto)
        self.spinCantidad = QtWidgets.QSpinBox(Frame)
        self.spinCantidad.setMinimumSize(QtCore.QSize(100, 50))
        self.spinCantidad.setMaximumSize(QtCore.QSize(100, 50))
        self.spinCantidad.setObjectName("spinCantidad")
        self.horizontalLayout.addWidget(self.spinCantidad)
        self.btnAnadir = QtWidgets.QPushButton(Frame)
        self.btnAnadir.setMinimumSize(QtCore.QSize(120, 50))
        self.btnAnadir.setMaximumSize(QtCore.QSize(120, 50))
        self.btnAnadir.setObjectName("btnAnadir")
        self.horizontalLayout.addWidget(self.btnAnadir)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.labelNombreProducto.setText(_translate("Frame", "Nombre Producto"))
        self.labelPrecioProducto.setText(_translate("Frame", "Precio Producto"))
        self.btnAnadir.setText(_translate("Frame", "Añadir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
