# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FrameContenedorMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(875, 325)
        Frame.setStyleSheet("QFrame{\n"
"    background-color: rgb(155, 222, 255);\n"
"}\n"
"\n"
"QLabel{\n"
"    \n"
"    background-color: rgb(0, 170, 255);\n"
"    font: 57 35pt \"Brush Script Std\";\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelNombreCategoria = QtWidgets.QLabel(Frame)
        self.labelNombreCategoria.setMinimumSize(QtCore.QSize(0, 100))
        self.labelNombreCategoria.setMaximumSize(QtCore.QSize(16777215, 100))
        self.labelNombreCategoria.setAlignment(QtCore.Qt.AlignCenter)
        self.labelNombreCategoria.setObjectName("labelNombreCategoria")
        self.verticalLayout.addWidget(self.labelNombreCategoria)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.labelNombreCategoria.setText(_translate("Frame", "Nombre de la categoria"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
