# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'metodo_pago.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrmPagar(object):
    def setupUi(self, FrmPagar):
        FrmPagar.setObjectName("FrmPagar")
        FrmPagar.resize(794, 527)
        self.centralwidget = QtWidgets.QWidget(FrmPagar)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 50, 771, 361))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.btnConfirmar = QtWidgets.QPushButton(self.centralwidget)
        self.btnConfirmar.setGeometry(QtCore.QRect(634, 460, 141, 51))
        self.btnConfirmar.setObjectName("btnConfirmar")
        self.btnCancelar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancelar.setGeometry(QtCore.QRect(480, 460, 141, 51))
        self.btnCancelar.setObjectName("btnCancelar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 422, 171, 16))
        self.label.setObjectName("label")
        self.comboMetPago = QtWidgets.QComboBox(self.centralwidget)
        self.comboMetPago.setGeometry(QtCore.QRect(200, 420, 181, 22))
        self.comboMetPago.setObjectName("comboMetPago")
        self.comboMetPago.addItem("")
        self.comboMetPago.addItem("")
        self.comboMetPago.addItem("")
        self.btnImprimir = QtWidgets.QPushButton(self.centralwidget)
        self.btnImprimir.setGeometry(QtCore.QRect(20, 460, 141, 51))
        self.btnImprimir.setObjectName("btnImprimir")
        self.lineEditTotal = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditTotal.setGeometry(QtCore.QRect(660, 420, 113, 20))
        self.lineEditTotal.setStyleSheet("font-size: 15px;")
        self.lineEditTotal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditTotal.setReadOnly(True)
        self.lineEditTotal.setObjectName("lineEditTotal")
        self.labelTotal = QtWidgets.QLabel(self.centralwidget)
        self.labelTotal.setGeometry(QtCore.QRect(600, 420, 51, 21))
        self.labelTotal.setObjectName("labelTotal")
        self.lbNombrePedido = QtWidgets.QLabel(self.centralwidget)
        self.lbNombrePedido.setGeometry(QtCore.QRect(14, 22, 141, 21))
        self.lbNombrePedido.setObjectName("lbNombrePedido")
        self.lineEditNombrePedido = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNombrePedido.setGeometry(QtCore.QRect(160, 23, 161, 20))
        self.lineEditNombrePedido.setStyleSheet("font-size:15px")
        self.lineEditNombrePedido.setText("")
        self.lineEditNombrePedido.setReadOnly(True)
        self.lineEditNombrePedido.setObjectName("lineEditNombrePedido")
        FrmPagar.setCentralWidget(self.centralwidget)

        self.retranslateUi(FrmPagar)
        QtCore.QMetaObject.connectSlotsByName(FrmPagar)

    def retranslateUi(self, FrmPagar):
        _translate = QtCore.QCoreApplication.translate
        FrmPagar.setWindowTitle(_translate("FrmPagar", "MainWindow"))
        self.btnConfirmar.setText(_translate("FrmPagar", "Confirmar"))
        self.btnCancelar.setText(_translate("FrmPagar", "Cancelar"))
        self.label.setText(_translate("FrmPagar", "<html><head/><body><p><span style=\" font-size:10pt;\">Seleccione Método de pago:</span></p></body></html>"))
        self.comboMetPago.setItemText(0, _translate("FrmPagar", "Efectivo"))
        self.comboMetPago.setItemText(1, _translate("FrmPagar", "Tarjeta"))
        self.comboMetPago.setItemText(2, _translate("FrmPagar", "QR"))
        self.btnImprimir.setText(_translate("FrmPagar", "Imprimir"))
        self.lineEditTotal.setText(_translate("FrmPagar", "0"))
        self.labelTotal.setText(_translate("FrmPagar", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">TOTAL:</span></p></body></html>"))
        self.lbNombrePedido.setText(_translate("FrmPagar", "<html><head/><body><p><span style=\" font-size:10pt;\">Nombre para el pedido:</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FrmPagar = QtWidgets.QMainWindow()
    ui = Ui_FrmPagar()
    ui.setupUi(FrmPagar)
    FrmPagar.show()
    sys.exit(app.exec_())
